// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReqNest.Infrastructure.Persistence;

#nullable disable

namespace ReqNest.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReqNestDbContext))]
    partial class ReqNestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReqNest.Core.Auditing.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("target_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_audit_events_tenant_id_created_at");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("ReqNest.Core.Identity.AccountToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_account_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_account_tokens_token_hash");

                    b.HasIndex("UserId", "Purpose", "ExpiresAt")
                        .HasDatabaseName("ix_account_tokens_user_id_purpose_expires_at");

                    b.ToTable("account_tokens", (string)null);
                });

            modelBuilder.Entity("ReqNest.Core.Identity.RoleGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllProjects")
                        .HasColumnType("boolean")
                        .HasColumnName("all_projects");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("GrantedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_user_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TenantMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_membership_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_role_grants");

                    b.HasIndex("TenantMembershipId", "Role", "AllProjects")
                        .HasDatabaseName("ix_role_grants_tenant_membership_id_role_all_projects");

                    b.ToTable("role_grants", (string)null);
                });

            modelBuilder.Entity("ReqNest.Core.Identity.RoleGrantProject", b =>
                {
                    b.Property<Guid>("RoleGrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_grant_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("RoleGrantId", "ProjectId")
                        .HasName("pk_role_grant_project");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_role_grant_project_project_id");

                    b.ToTable("role_grant_project", (string)null);
                });

            modelBuilder.Entity("ReqNest.Core.Identity.TenantMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("InvitationExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invitation_expires_at");

                    b.Property<string>("InvitationTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("invitation_token_hash");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_memberships");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tenant_memberships_user_id");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_memberships_tenant_id_user_id");

                    b.ToTable("tenant_memberships", (string)null);
                });

            modelBuilder.Entity("ReqNest.Core.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<int>("FailedSignInCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_sign_in_count");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastSignedInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_signed_in_at");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("password_hash");

                    b.Property<int>("PreferredLanguage")
                        .HasColumnType("integer")
                        .HasColumnName("preferred_language");

                    b.Property<int>("ThemePreference")
                        .HasColumnType("integer")
                        .HasColumnName("theme_preference");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ReqNest.Core.Identity.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_user_sessions_token_hash");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("ix_user_sessions_user_id_expires_at");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("ReqNest.Core.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeepLink")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("deep_link");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("event_key");

                    b.Property<string>("GroupKey")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("group_key");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.Property<string>("SummaryEnglish")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary_english");

                    b.Property<string>("SummaryFrench")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary_french");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("RecipientUserId", "EventKey")
                        .IsUnique()
                        .HasDatabaseName("ix_notifications_recipient_user_id_event_key");

                    b.HasIndex("TenantId", "RecipientUserId", "ReadAt")
                        .HasDatabaseName("ix_notifications_tenant_id_recipient_user_id_read_at");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("ReqNest.Core.Notifications.NotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CommentsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("comments_enabled");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DigestEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("digest_enabled");

                    b.Property<bool>("DueDateUpdatesEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("due_date_updates_enabled");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("WatcherUpdatesEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("watcher_updates_enabled");

                    b.HasKey("Id")
                        .HasName("pk_notification_preferences");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_preferences_tenant_id_user_id");

                    b.ToTable("notification_preferences", (string)null);
                });

            modelBuilder.Entity("ReqNest.Core.Reports.ReportExport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobName")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("blob_name");

                    b.Property<string>("ContainerName")
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("container_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("FilterSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("filter_snapshot_json");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("report_type");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_report_exports");

                    b.HasIndex("TenantId", "RequestedByUserId", "CreatedAt")
                        .HasDatabaseName("ix_report_exports_tenant_id_requested_by_user_id_created_at");

                    b.ToTable("report_exports", (string)null);
                });

            modelBuilder.Entity("ReqNest.Core.Tenancy.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DefaultAssigneeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_assignee_user_id");

                    b.Property<int>("DefaultPriority")
                        .HasColumnType("integer")
                        .HasColumnName("default_priority");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int?>("FirstResponseTargetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("first_response_target_minutes");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("key");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_english");

                    b.Property<string>("NameFrench")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_french");

                    b.Property<long>("NextTicketNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("next_ticket_number");

                    b.Property<int?>("ResolutionTargetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("resolution_target_minutes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("ix_projects_workflow_id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_tenant_id_key");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("ReqNest.Core.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DarkLogoBlobName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("dark_logo_blob_name");

                    b.Property<string>("DarkLogoContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dark_logo_content_type");

                    b.Property<int>("DefaultLanguage")
                        .HasColumnType("integer")
                        .HasColumnName("default_language");

                    b.Property<int>("DefaultTheme")
                        .HasColumnType("integer")
                        .HasColumnName("default_theme");

                    b.Property<string>("LogoBlobName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("logo_blob_name");

                    b.Property<string>("LogoContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("logo_content_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("primary_color");

                    b.Property<string>("ReportFooterText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("report_footer_text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("short_name");

                    b.Property<string>("SupportContact")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("support_contact");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("ReqNest.Core.Tickets.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("blob_name");

                    b.Property<string>("ChecksumSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checksum_sha256");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("container_name");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("original_file_name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("ScanStatus")
                        .HasColumnType("integer")
                        .HasColumnName("scan_status");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TicketCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_comment_id");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("TicketCommentId")
                        .HasDatabaseName("ix_attachments_ticket_comment_id");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_attachments_ticket_id");

                    b.HasIndex("TenantId", "BlobName")
                        .IsUnique()
                        .HasDatabaseName("ix_attachments_tenant_id_blob_name");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("ReqNest.Core.Tickets.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreationKey")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("creation_key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)")
                        .HasColumnName("description");

                    b.Property<string>("DescriptionPlainText")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)")
                        .HasColumnName("description_plain_text");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<DateTimeOffset?>("FirstRespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_responded_at");

                    b.Property<DateTimeOffset?>("FirstResponseTargetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_response_target_at");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("key");

                    b.PrimitiveCollection<string[]>("Labels")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("labels");

                    b.Property<long>("Number")
                        .HasColumnType("bigint")
                        .HasColumnName("number");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("ReporterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_user_id");

                    b.Property<string>("ResolutionSummary")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("resolution_summary");

                    b.Property<DateTimeOffset?>("ResolutionTargetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolution_target_at");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int>("SlaState")
                        .HasColumnType("integer")
                        .HasColumnName("sla_state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WorkflowStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_status_id");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("AssigneeUserId")
                        .HasDatabaseName("ix_tickets_assignee_user_id");

                    b.HasIndex("ReporterUserId")
                        .HasDatabaseName("ix_tickets_reporter_user_id");

                    b.HasIndex("WorkflowStatusId")
                        .HasDatabaseName("ix_tickets_workflow_status_id");

                    b.HasIndex("ProjectId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_tickets_project_id_number");

                    b.HasIndex("TenantId", "CreationKey")
                        .IsUnique()
                        .HasDatabaseName("ix_tickets_tenant_id_creation_key");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_tickets_tenant_id_key");

                    b.HasIndex("TenantId", "AssigneeUserId", "IsArchived")
                        .HasDatabaseName("ix_tickets_tenant_id_assignee_user_id_is_archived");

                    b.HasIndex("TenantId", "ProjectId", "WorkflowStatusId")
                        .HasDatabaseName("ix_tickets_tenant_id_project_id_workflow_status_id");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("ReqNest.Core.Tickets.TicketComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)")
                        .HasColumnName("body");

                    b.Property<string>("BodyPlainText")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)")
                        .HasColumnName("body_plain_text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ticket_comments");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("ix_ticket_comments_author_user_id");

                    b.HasIndex("TicketId", "CreatedAt")
                        .HasDatabaseName("ix_ticket_comments_ticket_id_created_at");

                    b.ToTable("ticket_comments", (string)null);
                });

            modelBuilder.Entity("ReqNest.Core.Tickets.TicketCommentRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EditedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("edited_by_user_id");

                    b.Property<string>("PreviousBody")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)")
                        .HasColumnName("previous_body");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TicketCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_comment_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ticket_comment_revisions");

                    b.HasIndex("TicketCommentId")
                        .HasDatabaseName("ix_ticket_comment_revisions_ticket_comment_id");

                    b.ToTable("ticket_comment_revisions", (string)null);
                });

            modelBuilder.Entity("ReqNest.Core.Tickets.TicketRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("SourceTicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_ticket_id");

                    b.Property<Guid>("TargetTicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_ticket_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ticket_relationships");

                    b.HasIndex("SourceTicketId", "TargetTicketId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_relationships_source_ticket_id_target_ticket_id_type");

                    b.ToTable("ticket_relationships", (string)null);
                });

            modelBuilder.Entity("ReqNest.Core.Tickets.TicketStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("FromStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_status_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<Guid>("ToStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_status_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ticket_status_history");

                    b.HasIndex("TicketId", "CreatedAt")
                        .HasDatabaseName("ix_ticket_status_history_ticket_id_created_at");

                    b.ToTable("ticket_status_history", (string)null);
                });

            modelBuilder.Entity("ReqNest.Core.Tickets.TicketWatcher", b =>
                {
                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_muted");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("TicketId", "UserId")
                        .HasName("pk_ticket_watchers");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ticket_watchers_user_id");

                    b.ToTable("ticket_watchers", (string)null);
                });

            modelBuilder.Entity("ReqNest.Core.Views.SavedView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ColumnsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("columns_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FiltersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("filters_json");

                    b.Property<string>("GroupBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("group_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("SortJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("sort_json");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_saved_views");

                    b.HasIndex("TenantId", "OwnerUserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_saved_views_tenant_id_owner_user_id_name");

                    b.ToTable("saved_views", (string)null);
                });

            modelBuilder.Entity("ReqNest.Core.Workflows.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workflows");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_workflows_project_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_workflows_tenant_id_name");

                    b.ToTable("workflows", (string)null);
                });

            modelBuilder.Entity("ReqNest.Core.Workflows.WorkflowStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsInitial")
                        .HasColumnType("boolean")
                        .HasColumnName("is_initial");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_terminal");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("key");

                    b.Property<string>("LabelEnglish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label_english");

                    b.Property<string>("LabelFrench")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label_french");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_statuses");

                    b.HasIndex("WorkflowId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_statuses_workflow_id_key");

                    b.HasIndex("WorkflowId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_statuses_workflow_id_order");

                    b.ToTable("workflow_statuses", (string)null);
                });

            modelBuilder.Entity("ReqNest.Core.Workflows.WorkflowTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CommentRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("comment_required");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FromStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_status_id");

                    b.Property<string>("NameEnglish")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name_english");

                    b.Property<string>("NameFrench")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name_french");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("ToStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_status_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_transitions");

                    b.HasIndex("FromStatusId")
                        .HasDatabaseName("ix_workflow_transitions_from_status_id");

                    b.HasIndex("ToStatusId")
                        .HasDatabaseName("ix_workflow_transitions_to_status_id");

                    b.HasIndex("WorkflowId", "FromStatusId", "ToStatusId")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_transitions_workflow_id_from_status_id_to_status_id");

                    b.ToTable("workflow_transitions", (string)null);
                });

            modelBuilder.Entity("ReqNest.Core.Identity.AccountToken", b =>
                {
                    b.HasOne("ReqNest.Core.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReqNest.Core.Identity.RoleGrant", b =>
                {
                    b.HasOne("ReqNest.Core.Identity.TenantMembership", "TenantMembership")
                        .WithMany("RoleGrants")
                        .HasForeignKey("TenantMembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_grants_tenant_memberships_tenant_membership_id");

                    b.Navigation("TenantMembership");
                });

            modelBuilder.Entity("ReqNest.Core.Identity.RoleGrantProject", b =>
                {
                    b.HasOne("ReqNest.Core.Tenancy.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_grant_project_projects_project_id");

                    b.HasOne("ReqNest.Core.Identity.RoleGrant", "RoleGrant")
                        .WithMany("ProjectScopes")
                        .HasForeignKey("RoleGrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_grant_project_role_grants_role_grant_id");

                    b.Navigation("Project");

                    b.Navigation("RoleGrant");
                });

            modelBuilder.Entity("ReqNest.Core.Identity.TenantMembership", b =>
                {
                    b.HasOne("ReqNest.Core.Tenancy.Tenant", "Tenant")
                        .WithMany("Memberships")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_memberships_tenants_tenant_id");

                    b.HasOne("ReqNest.Core.Identity.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_memberships_users_user_id");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReqNest.Core.Identity.UserSession", b =>
                {
                    b.HasOne("ReqNest.Core.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReqNest.Core.Notifications.Notification", b =>
                {
                    b.HasOne("ReqNest.Core.Identity.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_recipient_user_id");

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("ReqNest.Core.Tenancy.Project", b =>
                {
                    b.HasOne("ReqNest.Core.Tenancy.Tenant", "Tenant")
                        .WithMany("Projects")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_tenants_tenant_id");

                    b.HasOne("ReqNest.Core.Workflows.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_workflows_workflow_id");

                    b.Navigation("Tenant");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("ReqNest.Core.Tickets.Attachment", b =>
                {
                    b.HasOne("ReqNest.Core.Tickets.TicketComment", "TicketComment")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketCommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_attachments_ticket_comments_ticket_comment_id");

                    b.HasOne("ReqNest.Core.Tickets.Ticket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_tickets_ticket_id");

                    b.Navigation("Ticket");

                    b.Navigation("TicketComment");
                });

            modelBuilder.Entity("ReqNest.Core.Tickets.Ticket", b =>
                {
                    b.HasOne("ReqNest.Core.Identity.User", "AssigneeUser")
                        .WithMany()
                        .HasForeignKey("AssigneeUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tickets_users_assignee_user_id");

                    b.HasOne("ReqNest.Core.Tenancy.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_projects_project_id");

                    b.HasOne("ReqNest.Core.Identity.User", "ReporterUser")
                        .WithMany()
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_users_reporter_user_id");

                    b.HasOne("ReqNest.Core.Workflows.WorkflowStatus", "WorkflowStatus")
                        .WithMany()
                        .HasForeignKey("WorkflowStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_workflow_statuses_workflow_status_id");

                    b.Navigation("AssigneeUser");

                    b.Navigation("Project");

                    b.Navigation("ReporterUser");

                    b.Navigation("WorkflowStatus");
                });

            modelBuilder.Entity("ReqNest.Core.Tickets.TicketComment", b =>
                {
                    b.HasOne("ReqNest.Core.Identity.User", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_comments_users_author_user_id");

                    b.HasOne("ReqNest.Core.Tickets.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_comments_tickets_ticket_id");

                    b.Navigation("AuthorUser");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ReqNest.Core.Tickets.TicketCommentRevision", b =>
                {
                    b.HasOne("ReqNest.Core.Tickets.TicketComment", "TicketComment")
                        .WithMany("Revisions")
                        .HasForeignKey("TicketCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_comment_revisions_ticket_comments_ticket_comment_id");

                    b.Navigation("TicketComment");
                });

            modelBuilder.Entity("ReqNest.Core.Tickets.TicketStatusHistory", b =>
                {
                    b.HasOne("ReqNest.Core.Tickets.Ticket", "Ticket")
                        .WithMany("StatusHistory")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_status_history_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ReqNest.Core.Tickets.TicketWatcher", b =>
                {
                    b.HasOne("ReqNest.Core.Tickets.Ticket", "Ticket")
                        .WithMany("Watchers")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_watchers_tickets_ticket_id");

                    b.HasOne("ReqNest.Core.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_watchers_users_user_id");

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReqNest.Core.Workflows.Workflow", b =>
                {
                    b.HasOne("ReqNest.Core.Tenancy.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_workflows_projects_project_id");

                    b.HasOne("ReqNest.Core.Tenancy.Tenant", "Tenant")
                        .WithMany("Workflows")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workflows_tenants_tenant_id");

                    b.Navigation("Project");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ReqNest.Core.Workflows.WorkflowStatus", b =>
                {
                    b.HasOne("ReqNest.Core.Workflows.Workflow", "Workflow")
                        .WithMany("Statuses")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_statuses_workflows_workflow_id");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("ReqNest.Core.Workflows.WorkflowTransition", b =>
                {
                    b.HasOne("ReqNest.Core.Workflows.WorkflowStatus", "FromStatus")
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_transitions_workflow_statuses_from_status_id");

                    b.HasOne("ReqNest.Core.Workflows.WorkflowStatus", "ToStatus")
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_transitions_workflow_statuses_to_status_id");

                    b.HasOne("ReqNest.Core.Workflows.Workflow", "Workflow")
                        .WithMany("Transitions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_transitions_workflows_workflow_id");

                    b.Navigation("FromStatus");

                    b.Navigation("ToStatus");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("ReqNest.Core.Identity.RoleGrant", b =>
                {
                    b.Navigation("ProjectScopes");
                });

            modelBuilder.Entity("ReqNest.Core.Identity.TenantMembership", b =>
                {
                    b.Navigation("RoleGrants");
                });

            modelBuilder.Entity("ReqNest.Core.Identity.User", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("ReqNest.Core.Tenancy.Tenant", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Projects");

                    b.Navigation("Workflows");
                });

            modelBuilder.Entity("ReqNest.Core.Tickets.Ticket", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");

                    b.Navigation("StatusHistory");

                    b.Navigation("Watchers");
                });

            modelBuilder.Entity("ReqNest.Core.Tickets.TicketComment", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("ReqNest.Core.Workflows.Workflow", b =>
                {
                    b.Navigation("Statuses");

                    b.Navigation("Transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
